language: node_js
node_js:
    - "8"
    - "9"
install:
    - npm install -g @angular/cli
    - npm install -g webpack-cli
    - npm install -g protractor
    - npm install
    - webdriver-manager update
script:
    - npm run lint
    - npm run e2e
    - npm run build:ssr
